"""Remediation Prompt and Forensic Report Formatter."""

from __future__ import annotations

from typing import Any

from agent.analyzer.diff_analyzer import AnalysisResult
from agent.bridge.models import IntentEvent


def generate_remediation_markdown(
    journey_name: str,
    error: str,
    analysis: AnalysisResult,
    intents: list[IntentEvent],
    trace_path: str | None = None,
    video_path: str | None = None,
    dom_snapshot: str | None = None,
) -> str:
    """Produce a forensic-grade remediation markdown prompt ready to paste into Claude Code."""
    intent_lines: list[str] = []
    for it in intents[:3]:
        intent_lines.append(f"- **Prompt**: *{it.prompt_summary}*")
        intent_lines.append(f"  - **Intent**: {it.reasoning}")
        intent_lines.append(f"  - **Files**: `{', '.join(it.files)}`")
    intent_block = "\n".join(intent_lines) if intent_lines else "No bridge intent events logged."

    trace_line = f"`{trace_path}`" if trace_path else "Not recorded"
    video_line = f"`{video_path}`" if video_path else "Not recorded"
    dom_block = (
        f"```html\n{dom_snapshot[:500]}...\n```"
        if dom_snapshot
        else "*DOM state was not captured or was clean.*"
    )

    remediation_prompt = f"""You are fixing a regression caught by the Autonomous PR Testing Engine.

TEST JOURNEY FAILED: {journey_name}
ERROR: {error}
AFFECTED SURFACES: {', '.join(analysis.affected_surfaces)}

DEVELOPER INTENT BEHIND THE RECENT CHANGE:
{intent_block}

TASK:
1. Inspect the touched files: {', '.join(analysis.affected_surfaces)}
2. Fix the error so that the '{journey_name}' flow succeeds without breaking other flows.
3. Verify that expected elements render and inputs submit properly.
"""

    return f"""## 🚨 Autonomous PR Verification Failed: `{journey_name}`

> **Risk Assessment:** **{analysis.risk_tag.upper()} RISK**
> **Rationale:** {analysis.rationale}
> **Affected Surfaces:** {", ".join(f"`{s}`" for s in analysis.affected_surfaces)}

---

### 🔍 Forensic Evidence
- **Error:** `{error}`
- **Playwright Trace:** {trace_line} *(View with `npx playwright show-trace <file>`)*
- **Session Video:** {video_line}
- **DOM Snapshot at Failure:**
{dom_block}

---

### 🧠 Intent Context Hand-off
{intent_block}

---

### 📋 Ready-to-Paste Remediation Prompt
Copy and paste this into **Claude Code**, **Cursor**, or your coding agent to resolve the regression:

```markdown
{remediation_prompt.strip()}
```
"""


def generate_pr_summary_comment(
    status: str,
    passed_journeys: list[str],
    failed_journeys: list[dict[str, Any]],
    analysis: AnalysisResult,
    remediation_prompts: list[str],
) -> str:
    """Generate the GitHub PR comment summarizing the verification run."""
    icon = "✅" if status == "success" else "❌"
    header = f"## {icon} Autonomous PR Verification: **{status.upper()}**"

    body_parts = [header, ""]
    body_parts.append(f"**Risk Level:** `{analysis.risk_tag}` — {analysis.rationale}")
    body_parts.append("")

    if passed_journeys:
        body_parts.append("### ✅ Passed Journeys")
        for j in passed_journeys:
            body_parts.append(f"- `{j}`")
        body_parts.append("")

    if failed_journeys:
        body_parts.append("### ❌ Regressions Detected")
        for f in failed_journeys:
            body_parts.append(f"- `{f['name']}`: {f.get('error', 'Assertion failed')}")
        body_parts.append("")

    if remediation_prompts:
        body_parts.append("---")
        body_parts.append("### 🛠️ Forensic Proof & Remediation")
        for prompt in remediation_prompts:
            body_parts.append(prompt)
            body_parts.append("")

    body_parts.append("\n*Automated report generated by Autonomous PR Testing Engine via GitHub App.*")
    return "\n".join(body_parts)
