import React from "react";
import Link from "next/link";
import { ArrowLeft, ShieldCheck, FileText, CheckCircle2 } from "lucide-react";

export const metadata = {
  title: "Terms of Service — AutoQA",
  description: "Terms and conditions governing the use of the AutoQA verification platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#fafaf9] text-slate-900 font-sans selection:bg-slate-200">
      <header className="border-b border-slate-200 bg-white px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link
              href="/"
              className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-600 hover:text-slate-900 transition-colors rounded-md border border-slate-200 px-2.5 py-1.5 bg-slate-50"
            >
              <ArrowLeft className="h-3.5 w-3.5" />
              <span>Back to AutoQA</span>
            </Link>
          </div>
          <span className="font-mono text-xs text-slate-500">Effective: September 2026</span>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-12 space-y-8">
        <div className="space-y-2 border-b border-slate-200 pb-6">
          <div className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-0.5 text-xs font-semibold text-emerald-700 border border-emerald-200 mb-2">
            <FileText className="h-3.5 w-3.5" />
            Legal Agreement
          </div>
          <h1 className="text-3xl font-extrabold tracking-tight text-slate-950">
            Terms of Service
          </h1>
          <p className="text-sm text-slate-600 leading-relaxed">
            Please read these terms carefully before accessing or using the AutoQA autonomous PR testing platform.
          </p>
        </div>

        <section className="space-y-4 text-sm text-slate-700 leading-relaxed">
          <h2 className="text-lg font-bold text-slate-950">1. Acceptance of Terms</h2>
          <p>
            By connecting a GitHub repository, signing in with Supabase Auth, or triggering test journeys via the Coding Agent Bridge, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not access or use AutoQA.
          </p>

          <h2 className="text-lg font-bold text-slate-950">2. Autonomous Verification & Sandboxing</h2>
          <p>
            AutoQA provisions ephemeral containerized browser environments to execute intent-driven functional, visual, and performance verifications on pull request branches and authorized web endpoints. You represent and warrant that you hold lawful rights to test any repository or domain you connect to the service.
          </p>

          <h2 className="text-lg font-bold text-slate-950">3. Multi-Role Credentials & Secret Handling</h2>
          <p>
            Test role credentials configured in Repository Settings are encrypted at rest using industry-standard AES-256 vault encryption. Test credentials must never represent live production root or financial administrator credentials. AutoQA automatically redacts authorization headers and passwords in forensic waterfall logs.
          </p>

          <h2 className="text-lg font-bold text-slate-950">4. Service Availability & Synthesized Patches</h2>
          <p>
            Fix proposals and remediation patches generated by AutoQA are synthesized recommendations derived from Playwright journey traces and AST analysis. You retain full responsibility for reviewing, testing, and approving any patch before merging it into your production codebases.
          </p>

          <h2 className="text-lg font-bold text-slate-950">5. Limitation of Liability</h2>
          <p>
            In no event shall AutoQA or its contributors be liable for indirect, incidental, special, consequential, or punitive damages resulting from software deployments, failed build pipelines, or test execution outcomes.
          </p>
        </section>

        <div className="pt-8 border-t border-slate-200 text-xs text-slate-500 flex items-center justify-between">
          <p>© 2026 AutoQA Platform. All rights reserved.</p>
          <div className="flex gap-4">
            <Link href="/privacy" className="hover:underline">Privacy Policy</Link>
            <Link href="/security" className="hover:underline">Security Overview</Link>
          </div>
        </div>
      </main>
    </div>
  );
}
